### ISSUE TITLE
XSRF Token Validation Failed

### ISSUE THREAD

**Issue by glaciyan** [evaera/roblox-animation-transfer#10]
Hello,
we tried porting animations from a user account to our group. But doing that threw an error along the lines of:
`AnimationName: XSRF Token Validation Failed`
I made sure that I used the correct ROBLOSECURITY cookie, I also tried using the ROBLOSECURITY cookie with and without the warning.
What I've also tried was using an older commands from my history which worked fine back then  a44c7dd934b889fd4a37a364415c5e9ae3f7018e and replaced the -c flag value with my current ROBLOSECURITY cookie.
Command which I used in Powershell:
`npx tsc`
`node ./dist/index.js -g [groupid] -i animationList.txt -o out.txt -c "[ROBLOSECURITY cookie]"`

**Comment by evaera** [comment]
Fixed
