### ISSUE TITLE
If an animation fails to upload because of bad name/description

### ISSUE THREAD

**Issue by NNickey** [evaera/roblox-animation-transfer#15]
Next upload attempt should just leave the upload name as Keyframe Sequence awhile keeping the name in the txt file.

**Comment by NNickey** [comment]
Meanwhile, if an outfile already exists, DONT OVERWRITE IT, append and possibly that it should check if the animation has already been transferred?

**Comment by evaera** [comment]
These seem like two separate issues! Could you open a second issue?

Also, if you want to help contribute these features yourself, feel free to create a PR.

**Comment by evaera** [comment]
> Meanwhile, if an outfile already exists, DONT OVERWRITE IT, append and possibly that it should check if the animation has already been transferred?

Instead of specifying `-o` or `--outFile`, just use `roblox-animation-transfer -u 1234 -l >> out.txt`. This will append instead of overwriting. This is built into bash.

**Comment by NNickey** [comment]
Didn't know if this GitHub was active, figured to condense my suggestions. I'll see about it
