### ISSUE TITLE
How to put in .ROBLOSECURITY Cookie?

### ISSUE THREAD

**Issue by BlaiseBunny** [evaera/roblox-animation-transfer#2]
I'm doing "export ROBLOSECURITY=[Everything after _|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_] but when I do the list command it says that it is unable to log in with the provided cookie.

**Comment by evaera** [comment]
What shell are you using?

**Comment by evaera** [comment]
Also, why did you put square brackets? Only include your cookie, please don't wrap in square brackets.

**Comment by BlaiseBunny** [comment]
I'm using Git bash and i'm not putting the square brackets

**Comment by evaera** [comment]
Make sure you run `export ROBLOSECURITY="entire cookie here"` and ensure you haven't spelled anything incorrectly.

Going to close this now as there is nothing wrong with the package.

**Comment by ypurpl** [comment]
So to make this clear (sorry for opening) you have to enter the whole thing, including the WARNING-DO-NOT-SHARE-THIS part?

**Comment by evaera** [comment]
yes

**Comment by ddindindcduin** [comment]
sorry for opening but can you explain how i do this?

**Comment by Elijah32131** [comment]
I still dont get how to beem accts

**Comment by Elijah32131** [comment]
can someone help me
pls

**Comment by Literallyahelplessguy** [comment]
Is it possible to use cookies on mobile?

**Comment by ElliottSherbourne** [comment]
this didnt work for me, im using mac would this change anything?
also i used export ROBLOSECURITY="cookie" but i got just got 'Uncaught SyntaxError: Unexpected token 'export'

**Comment by evaera** [comment]
You can look up documentation on how environment variables work in the shell you're using.

> this didnt work for me, im using mac would this change anything? also i used export ROBLOSECURITY="cookie" but i got just got 'Uncaught SyntaxError: Unexpected token 'export'

**Comment by leekylo** [comment]
_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_6CC1BA8AB35E1AF9892DCC72093C5D87A1C100AA158E07116AA0A2B27716ABC4F92BB0734CE0E68E9294643D85B3E4F0044850995CA41EBB7ABA5F53F9A114B9431FFCD11EDCCC8E75233729487AA3C6FED0ECCD785391C968BC7F9052C6948CE0F2158671B1FD2FDEF679A66B5D1F7CED5184AE852B5432A5F52BA2E7A4362FB802438EF85E0630A3D8D11DCFB66183EF0017E9F436EBB51631606FB1120BA669B373EA14EEA9CE21E976DC4816AFCACBFC881E4227A73E43B4B49183490096BE71B8597E25ECA75EC9B249C9A5011D027F5A5DEEF386AC2A55324A3CDAD9D82254593D2A29CED5CFB1979C34B5D1FF19265868BBE1B60425F486D6149E8A5530028659E0CE00BE16289B33414639A4B451F6DE4F936BC18FC9DFA5CEF3DD61908AC778A4C0AF04EB9BC80289A1E447A4600AB1059651AC84F9D4821E40372081191509E531FAB31E03E2B235BBC0BF121EB493
